#!/usr/bin/env bash
\cp -f ./Relaxation/Experiments/figure-4A/merge_all/Stability.pdf ./manuscript/artworks/Relaxation-Stability-Alpha-Gamma.pdf
\cp -f ./Relaxation/Experiments/Supp-7-1/merge_all/Stability.pdf ./manuscript/artworks/Relaxation-Stability-Alpha.pdf
\cp -f ./Relaxation/Experiments/Supp-7-2/merge_all/Stability.pdf ./manuscript/artworks/Relaxation-Stability.pdf
\cp -f ./Relaxation/Experiments/Supp-7-3/merge_all/Stability.pdf ./manuscript/artworks/Relaxation-Stability-Gamma.pdf
\cp -f ./Relaxation/Experiments/Supp-7-4/merge_all/Stability.pdf ./manuscript/artworks/Relaxation-Stability-Grantham-Alpha-Gamma.pdf
\cp -f ./Scaling/Experiments/figure-3A/heatmap_SimuStab_plot/dnd0_event_tot.pdf ./manuscript/artworks/SimuStab-Alpha-Gamma-Elasticity.pdf
\cp -f ./Heatmap/Experiments/figure-3A/heatmap_SimuStab_plot/dnd0_event_tot.pdf ./manuscript/artworks/SimuStab-Grantham-Gamma-Elasticity.pdf
\cp -f ./Heatmap/Experiments/figure-3B/heatmap_SimuStab_plot/dnd0_event_tot.pdf ./manuscript/artworks/SimuStab-Grantham-Alpha-Elasticity.pdf
\cp -f ./Heatmap/Experiments/figure-3C/heatmap_SimuFold_plot/dnd0_event_tot.pdf ./manuscript/artworks/SimuFold-Elasticity.pdf
\cp -f ./Heatmap/Experiments/figure-3C/heatmap_SimuFold_plot/sub-ΔG-mean.pdf ./manuscript/artworks/SimuFold-Elasticity-DG.pdf
\cp -f ./Heatmap/Experiments/figure-3C/DG-DDG.pdf ./manuscript/artworks/SimuFold-DG-DDG.pdf
\cp -f ./Heatmap/Experiments/figure-3D/heatmap_SimuStab_plot/dnd0_event_tot.pdf ./manuscript/artworks/SimuStab-Grantham-Elasticity.pdf
\cp -f ./Heatmap/Experiments/figure-3D/heatmap_SimuStab_plot/sub-ΔG-mean.pdf ./manuscript/artworks/SimuStab-Elasticity-DG.pdf
\cp -f ./Heatmap/Experiments/figure-3D/DG-DDG.pdf ./manuscript/artworks/SimuStab-DG-DDG.pdf
\cp -f ./Heatmap/Experiments/figure-4B/merge_all/Stability.pdf ./manuscript/artworks/Relaxation-DFE-Profile-N500.pdf
\cp -f ./Heatmap/Experiments/Supp-6-1/heatmap_SimuDfe_plot/dnd0_event_tot.pdf ./manuscript/artworks/SimuDfe-Elasticity.pdf
\cp -f ./Heatmap/Experiments/Supp-6-2/heatmap_SimuProfile_plot/dnd0_event_tot.pdf ./manuscript/artworks/SimuProfile-Elasticity.pdf
\cp -f ./Heatmap/Experiments/Supp-6-3/heatmap_SimuStab_plot/dnd0_event_tot.pdf ./manuscript/artworks/SimuStab-Elasticity.pdf
\cp -f ./Heatmap/Experiments/Supp-6-4/heatmap_SimuStab_plot/dnd0_event_tot.pdf ./manuscript/artworks/SimuStab-Grantham-Beta-Elasticity.pdf
\cp -f ./Heatmap/Experiments/Supp-6-5/heatmap_SimuStab_plot/dnd0_event_tot.pdf ./manuscript/artworks/SimuStab-Grantham-Nsite-Elasticity.pdf
\cp -f ./Heatmap/Experiments/Supp-6-6/heatmap_SimuStab_plot/dnd0_event_tot.pdf ./manuscript/artworks/SimuStab-Grantham-Gamma-Elasticity-ExpressionLevel.pdf
\cp -f ./Heatmap/Experiments/Supp-6-7/heatmap_SimuStab_plot/dnd0_event_tot.pdf ./manuscript/artworks/SimuStab-Grantham-GammaStd-Elasticity.pdf
\cp -f ./Heatmap/Experiments/Supp-6-8/heatmap_SimuStab_plot/dnd0_event_tot.pdf ./manuscript/artworks/SimuStab-GammaStd-Elasticity.pdf
\cp -f ./Heatmap/Experiments/Supp-8-1/merge/SimuStab_1_1_seed.tsv.DFE.density.pdf ./manuscript/artworks/DFE-SimuStab-Grantham-GammaStd.pdf
\cp -f ./Heatmap/Experiments/Supp-8-1/merge/SimuStab_1_1_seed.tsv.mut-ΔΔG.density.pdf ./manuscript/artworks/DPE-SimuStab-Grantham-GammaStd.pdf
