EXPERIMENT:
  COMPILE: false
  NE_PARAM_MAGNITUDE: 4
  NE_PARAM_STEPS: 15
  GAMMA_PARAM_MAGNITUDE: 1
  GAMMA_PARAM_STEPS: 5
  REPLICATES: 50
PARAMS:
  EXON_SIZE: 300
  POPULATION_SIZE: 100000
  ALPHA: -40.0
  GAMMA: 0.32
  GAMMA_STD: 0.32
  BETA: 1.686
SimuStab:
  NUC_MATRIX: SimuEvol/data/matrices/nucleotide_GTR.tsv
  PRECISION_MATRIX: SimuEvol/data/matrices/precision3x3.tsv
  NBR_BRANCHES: 3
  MUTATION_RATE_PER_GENERATION: 1.0e-8
  GENERATION_TIME: 1
  ROOT_AGE: 300e6
  NBR_EXONS: 1
  GRANTHAM: false
ToyStab:
  NBR_STATES: 20
