EXPERIMENT:
  COMPILE: false
  EXON_SIZE_MAGNITUDE: 2
  EXON_SIZE_STEPS: 25
  REPLICATES: 200
PARAMS:
  SCALE_GAMMA: false
  SCALE_ALPHA: true
  EXON_SIZE: 100
  POPULATION_SIZE: 100000.0
  ALPHA: -10.0
  GAMMA: 0.1
  GAMMA_STD: 0.0
  BETA: 1.686
  GRANTHAM: false
  NUC_MATRIX: SimuEvol/data/matrices/nucleotide_GTR.tsv
  PRECISION_MATRIX: SimuEvol/data/matrices/precision3x3.tsv
  NBR_BRANCHES: 3
  MUTATION_RATE_PER_GENERATION: 1.0e-8
  GENERATION_TIME: 1
  ROOT_AGE: 300e6
  BIAS_POP_SIZE: 3.0
  NBR_EXONS: 1