EXPERIMENT:
  COMPILE: false
  SIMULATORS: [SimuStab]
  X_PARAM: DDG
  X_PARAM_TYPE: float
  X_PARAM_MAGNITUDE: 2
  Y_PARAM: EXON_SIZE
  Y_PARAM_TYPE: int
  Y_PARAM_MAGNITUDE: 2
  HEATMAP_GRID_STEP: 9
  REPLICATES: 5
SIMULATION:
  NBR_BRANCHES: 2
  PREFERENCES: SimuEvol/data/preferences/np_1800_498.prefs
  NUC_MATRIX: SimuEvol/data/matrices/nucleotide_GTR.tsv
  PRECISION_MATRIX: SimuEvol/data/matrices/precision3x3.tsv
  MUTATION_RATE_PER_GENERATION: 1.0e-8
  ROOT_AGE: 200e6
  GENERATION_TIME: 1
  EXON_SIZE: 300
  BRANCH_WISE_CORRELATION: true
  BIAS_POP_SIZE: 0.0
  BIAS_MUT_RATE: 0.0
  BIAS_GEN_TIME: 0.0
  FIXED_POP_SIZE: true
  FIXED_MUT_RATE: true
  FIXED_GEN_TIME: true
SimuFold:
  PDB_FOLDER: SimuEvol/data/pdbfiles
  NBR_EXONS: 6
  NBR_GRID_STEP: 100
  POPULATION_SIZE: 1e5
  CUT_OFF: 7.0
SimuStab:
  NBR_EXONS: 6
  NBR_GRID_STEP: 100
  POPULATION_SIZE: 1e3
  DG_MIN: -10
  DDG: 0.1
SimuDiv:
  POPULATION_SIZE: 1.0
  NBR_GRID_STEP: 100
SimuGeo:
  NBR_GRID_STEP: 100
  POPULATION_SIZE: 30.0
  COMPLEXITY: 5
  NBR_EXONS: 6
SimuPoly:
  BETA: 1.0
  POPULATION_SIZE: 5000
  SAMPLE_SIZE: 20
  NOISE_SIGMA: 0.0
  NOISE_THETA: 0.9