EXPERIMENT:
  COMPILE: false
  SIMULATORS: [SimuDfe]
  X_PARAM: {POPULATION_SIZE: double}
  X_PARAM_REVERSE: {}
  X_PARAM_MAGNITUDE: 2
  X_PARAM_STEPS: 9
  Y_PARAM: {GAMMA_SHAPE: double}
  Y_PARAM_REVERSE: {}
  Y_PARAM_MAGNITUDE: 1
  Y_PARAM_STEPS: 3
  REPLICATES: 10
SIMULATION:
  NBR_BRANCHES: 2
  PREFERENCES: SimuEvol/data/preferences/np_1800_498.prefs
  NUC_MATRIX: SimuEvol/data/matrices/nucleotide_GTR.tsv
  PRECISION_MATRIX: SimuEvol/data/matrices/precision3x3.tsv
  MUTATION_RATE_PER_GENERATION: 1.0e-8
  ROOT_AGE: 200e6
  GENERATION_TIME: 1
  EXON_SIZE: 300
  BRANCH_WISE_CORRELATION: true
  BIAS_POP_SIZE: 0.0
  BIAS_MUT_RATE: 0.0
  BIAS_GEN_TIME: 0.0
  FIX_POP_SIZE: true
  FIX_MUT_RATE: true
  FIX_GEN_TIME: true
SimuProfile:
  POPULATION_SIZE: 1.0
  NBR_GRID_STEP: 100
SimuDfe:
  NBR_EXONS: 6
  POPULATION_SIZE: 1e4
  GAMMA_REFLECTED: true
  GAMMA_MEAN: 4.0e-5
  GAMMA_SHAPE: 0.5
SimuFold:
  PDB_FOLDER: SimuEvol/data/pdbfiles
  NBR_EXONS: 6
  NBR_GRID_STEP: 100
  POPULATION_SIZE: 1e5
  CUT_OFF: 7.0
SimuStab:
  NBR_EXONS: 6
  NBR_GRID_STEP: 100
  POPULATION_SIZE: 1e4
  DG_MIN: -199.0
  DDG: 1.686
SimuGeo:
  NBR_GRID_STEP: 100
  POPULATION_SIZE: 1e4
  COMPLEXITY: 1
  PEAKNESS: 1e-3
  EPISTASIS: 2.0
  RADIUS: 0.1
  RADIUS_STD: 0.0
  NBR_EXONS: 6
PolyProfile:
  BETA: 1.0
  POPULATION_SIZE: 5000
  SAMPLE_SIZE: 20
  NOISE_SIGMA: 0.0
  NOISE_THETA: 0.9
PolyDfe:
  POPULATION_SIZE: 1000
  SAMPLE_SIZE: 20
  NOISE_SIGMA: 0.0
  NOISE_THETA: 0.9
  NBR_EXONS: 6
  GAMMA_REFLECTED: false
  GAMMA_MEAN: 4.0e-4
  GAMMA_SHAPE: 0.5
TOY:
  NBR_SITES: 300
ToyStab:
  POPULATION_SIZE: 1e4
  DG_MIN: -199.0
  DDG: 1.686
  NBR_STATES: 2
ToyGeo:
  POPULATION_SIZE: 1e4
  PEAKNESS: 1e-3
  EPISTASIS: 2.0
  RADIUS: 0.1